<?php

class Bairros
{
  private array $bairros = [
    "Água Fria" => [],
    "Aeroclube" => [],
    "Altiplano" => [],
    "Alto do Céu" => [],
    "Alto do Mateus" => [],
    "Anatólia" => [],
    "Bairro das Indústrias" => [],
    "Bairro dos Estados" => [],
    "Bairro dos Ipês Norte" => [],
    "Bairro dos Novais" => [],
    "Bancários" => [
      "Portal do Sol",
      "Anatólia",
      "Jardim Cidade Universitária",
      "Mangabeira",
      "Castelo Branco",
      "Cabo Branco",
      "Manaíra",
      "Miramar"
    ],
    "Barra de Gramame" => [],
    "Bessa" => [],
    "Brisamar" => [],
    "Cabo Branco" => [],
    "Castelo Branco" => [],
    "Centro Norte" => [],
    "Cidade dos Colibris" => [],
    "Costa do Sol" => [],
    "Costa e Silva" => [],
    "Cristo Redentor" => [],
    "Cruz das Armas" => [],
    "Cuiá" => [],
    "Distrito Industrial" => [],
    "Ernesto Geisel" => [],
    "Ernâni Sátiro" => [],
    "Expedicionários" => [],
    "Funcionários II" => [],
    "Funcionários III" => [],
    "Gramame Sul" => [],
    "Grotão Sul" => [],
    "Ilha do Bispo" => [],
    "Jaguaribe" => [],
    "Jardim 13 de Maio" => [],
    "Jardim Cidade Universitária" => [],
    "Jardim Esther" => [],
    "Jardim Luna" => [],
    "Jardim Mangueira" => [],
    "Jardim Oceania" => [],
    "Jardim Planalto" => [],
    "Jardim São Paulo" => [],
    "Jardim Veneza" => [],
    "José Américo" => [],
    "João Agripino" => [],
    "João Paulo II" => [],
    "Manaíra" => [],
    "Mandacaru" => [],
    "Mangabeira" => [],
    "Mata do Buraquinho" => [],
    "Miramar" => [],
    "Mumbaba" => [],
    "Mussuré" => [],
    "Muçumagro" => [],
    "Oitizeiro" => [],
    "Padre Zé" => [],
    "Paratibe" => [],
    "Pedro Gondim" => [],
    "Penha" => [],
    "Planalto da Boa Esperança" => [],
    "Ponta dos Seixas" => [],
    "Portal do Sol" => [],
    "Rangel Oeste" => [],
    "Róger Norte" => [],
    "São José" => [],
    "Tambaú" => [],
    "Tambauzinho" => [],
    "Tambiá" => [],
    "Torre" => [],
    "Trincheiras" => [],
    "Valentina Figueiredo" => [],
    "Varadouro" => [],
    "Varjão Oeste" => []
  ];

  function getBairros()
  {
    return $this->bairros;
  }
}
